[package]
name = "langs"
version = "0.1.0"
authors = ["Michael Mokrysz <hi@46b.it>"]

[dependencies]
# PATH="/usr/local/Cellar/llvm/5.0.1/bin:$PATH"
llvm-sys = "50"
nom = "3.2.1"
quickcheck = "0.2"
rand = "0.3.20"
